country: china
province: beijing
city: beijing
area: haidian

party: true

birthday: 1949-10-01

user1:
  name: itcast
  age: 16

user2:
  name: itheima
  age: 16


a:
  b:
    c:
      d:
        e: 123

likes:
  - game
  - music
  - sleep

likes2: [game,music,sleep]

users:
  - name: zhangsan
    age: 18
  - name: lisi
    age: 17

users3: [{name:zhangsan,age:18},{name:lisi,age:17}]

users2:
  -
    name: zhangsan
    age: 18
  -
    name: lisi
    age: 17
server:
  port: 8080
  servlet:
    context-path: /test123

baseDir: c:\win10

#??${???}????
tempDir: ${baseDir}\temp
#???????????????????????
tempDir2: "${baseDir}\temp \t1 \t2 \t3"

#???????????
#?spring?????????????????spring??????
#??????spring?????????
datasource:
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost/spring_db
  username: root
  password: 123456